### ISSUE TITLE
type_check_date function doesn't work

### ISSUE THREAD

**Issue by ea-rus** [mindsdb/type_infer#53] opened 2023-10-04 15:10 UTC
Steps to replicate
```python
df = pd.DataFrame([{'month': '2017-07-01'}, {'month': '2017-08-01'}, {'month': '2017-09-01'}])

import type_infer
type_infer.infer.type_check_date(df['month'])
```
Raises:
```
  File "/work/mindsdb/mindsdb_main/venv/lib/python3.10/site-packages/type_infer/infer.py", line 135, in type_check_date
    if dt.hour == 0 and dt.minute == 0 and dt.second == 0 and len(str(element)) <= 16:
  File "/work/mindsdb/mindsdb_main/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'hour'
```

**Comment by paxcema** [comment] 2023-10-04 15:26
Related: [mindsdb#7419](https://github.com/mindsdb/mindsdb/pull/7419). Once this is solved, we should change the linked code so that it uses `type_infer` instead.

**Comment by pedrofluxa** [comment] 2023-10-04 18:57
The function `type_check_date` is intended to work with a single element, that is, non `iterable` objects. 

This issue arises when calling the function with a `pandas.Series` (which is `iterable`), which is a perfectly valid use case for `pandas.to_datetime()` but makes the function crash as `pandas.to_datetime()` returns a `pandas.Series` when called with a `pandas.Series` as argument. This is in opposition to the intended functionality, which is to be called with a single element as argument. 

The following code works as intended

```
import pandas as pd
import type_infer

df = pd.DataFrame([{'month': '2017-07-01'}, {'month': '2017-08-01'}, {'month': '2017-09-01'}])
for element in df['month']:
    print(type_infer.infer.type_check_date(element))
``` 

which outputs (in `ipython`)

```
datetime
datetime
datetime
```

Shall the user require support to check the type of a `pandas.Series` using this function, please let me know :)

**Comment by paxcema** [comment] 2023-10-04 19:01
Closing as `won't fix`, not an actual issue.

**Closed as completed by paxcema** 2023-10-04 19:01 UTC
Labels: wontfix
